version: "3.3"
services:
 frontend:
   container_name: qurryfrontend
   image: frontend:v1
   ports:
    - "8080:80"
   

 backend:
    image: backend:v1
    container_name : qurrybackend
    restart: always
    ports:
      - "8081:8081"
      
   
    volumes :
      - /home/jegan/Desktop/data:/var/lib/postgresql/data
